api/urls.py
from django.urls import include, path, re_path
from .views import *
from rest_framework import routers

app_name = "api"

router = routers.DefaultRouter()
urlpatterns = [
    re_path(r'^foodservice$', FoodServiceList.as_view(), name='foodservice'),
    re_path(r'^travelservice$', TravelServiceList.as_view(), name='travelservice'),
    re_path(r'^shoppingservice$', ShoppingServiceList.as_view(), name='shoppingservice'),
    re_path(r'^eventservice$', EventServiceList.as_view(), name='eventservice'),
    re_path(r'^otherservice$', OtherServiceList.as_view(), name='otherservice'),
    re_path(r'^get_coordinates$', get_coordinates, name='get_coordinates'),

    re_path(r'^foodservicereco$', FoodServiceReco.as_view(), name='foodservicereco'),
    re_path(r'^travelservicereco$', TravelServiceReco.as_view(), name='travelservicereco'),
    re_path(r'^shoppingservicereco$', ShoppingServiceReco.as_view(), name='shoppingservicereco'),

]

groups/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required
from pool.models import Group

app_name = "groups"

urlpatterns = [
    path('', grouphome.as_view(), name='home'),
    path('display/<slug:pk>', GroupListView.as_view(), name='display'),
    path('remove_member/<int:g_id>/<int:user_id>', remove_member, name='remove_member'),
    path('create', GroupCreateView.as_view(), name='create'),
    path('join/<int:hash>', group_join, name='join')
]

pool/urls.py
from django.urls import path
from .views import *
from chat.views import food_index

app_name = "pool"

urlpatterns = [
    # path('create', ServiceCreateView.as_view(),name='create')
    # path('', home, name='home')
    path('', home, name='home')    # Making My Services the home page
]

services/urls.py
from django.urls import path
from .views import *

app_name = "services"

urlpatterns = [
    # path('create', ServiceCreateView.as_view(), name="create"),
    path('foodcreate', FoodCreateView.as_view(), name="foodcreate"),
    path('shoppingcreate', ShoppingCreateView.as_view(), name="shoppingcreate"),
    path('travelcreate', TravelCreateView.as_view(), name="travelcreate"),
    path('eventcreate', EventCreateView.as_view(), name="eventcreate"),
    path('othercreate', OtherCreateView.as_view(), name="othercreate"),
    path('groupselect', GroupSelectView.as_view(), name="groupselect"),
    path('food_autocomplete/', FoodVendorAutocomplete.as_view(), name='food-autocomplete'),
    path('shopping_autocomplete/', ShoppingVendorAutocomplete.as_view(), name='shopping-autocomplete'),
    path('location_autocomplete/', LocationAutocomplete.as_view(), name='location-autocomplete'),
]

superpool/urls.py
from django.contrib import admin
from django.urls import path, include
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('pool.urls')),
    path('groups/',include('groups.urls')),
    path('services/', include('services.urls')),
    path('chat/', include('chat.urls')),
    path('notification/', include('notification.urls')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('api/', include('api.urls')),
    path('activities/', include('activities.urls')),
    path('recommendations/', include('recommendations.urls')),
    path('location/', include('location.urls'))
]

pool/models.py
from django.db import models
from django.core.validators import validate_comma_separated_integer_list
from polymorphic.models import PolymorphicModel
from django import forms
from accounts.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Group(models.Model):
    admin = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1000, default='')
    hash = models.IntegerField(default=0)
    members = models.ManyToManyField(User,
                                     through="GroupMember",
                                     through_fields=("group", "user"),
                                     related_name="groops")

    def __str__(self):
        return f'{self.name}'


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'description']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)


class Restaurant(models.Model):
    name = models.CharField(null=False, max_length=1000)
    price = models.FloatField(null=True)
    cusine_category = models.CharField(null=True, max_length=500)
    city = models.CharField(null=True, max_length=100)
    region = models.CharField(null=True, max_length=100)
    url = models.URLField(null=True)
    page_no = models.IntegerField(null=True)
    cusine_type = models.CharField(null=True, max_length=100)
    timing = models.CharField(null=True, max_length=100)
    rating = models.CharField(null=True, max_length=100)
    votes = models.CharField(null=True, max_length=100)

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(null=False, max_length=1000)
    domain = models.CharField(max_length=100)
    logo = models.URLField(null=True)
    timestamp = models.DateTimeField(null=True)

    def __str__(self):
        return self.name


class Location(models.Model):
    latitude = models.DecimalField(null=False, max_digits=10, decimal_places=7)
    longitude = models.DecimalField(null=False, max_digits=10, decimal_places=7)
    address = models.CharField(default='', max_length=1000)
    timestamp = models.DateTimeField(null=False)

    def __str__(self):
        return self.address


class Service(PolymorphicModel):
    # group_ids = models.CharField(validators=[validate_comma_separated_integer_list],
    #                              max_length=200, blank=True, null=True, default='')
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name="%(class)s_services")
    initiator = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)
    # slackness = models.DurationField(null=True)
    description = models.CharField(null=False, max_length=1000)  # this is a general description
    # stype = models.CharField(null=False, max_length=255)  # one among ['Food','Travel','Shopping']
    members = models.ManyToManyField(User,
                                     through="ServiceMember",
                                     through_fields=("service_id", "user_id"),
                                     related_name="service_member")
    groups = models.ManyToManyField(Group,
                                    through="ServiceGroup",
                                    through_fields=("service", "group"),
                                    related_name="group_of_service")

    def __str__(self):
        return self.description

    def get_members(self):
        return "\n".join([p.products for p in self.members.all()])

    @property
    def group_name(self):
        """
        Returns the Channels Group name that sockets should subscribe to to get sent
        messages as they are generated.
        """
        return "room-%s" % self.id


class ServiceGroup(models.Model):
    service = models.ForeignKey(Service, on_delete=models.DO_NOTHING)
    group = models.ForeignKey(Group, on_delete=models.DO_NOTHING)


class TravelService(Service):
    start_point = models.ForeignKey(Location, on_delete=models.DO_NOTHING, null=False, related_name='start_loc')
    end_point = models.ForeignKey(Location, on_delete=models.DO_NOTHING, null=False, related_name='end_loc')
    TRAVEL_CHOICES = [
        ('Taxi', 'Taxi'),
        ('Train', 'Train'),
        ('Flight', 'Flight'),
    ]
    transport = models.CharField(max_length=10, choices=TRAVEL_CHOICES, null=True)

    def __str__(self):
        return '%s' % self.transport


class FoodService(Service):
    vendor = models.ForeignKey(Restaurant, on_delete=models.DO_NOTHING, null=False)

    def __str__(self):
        return '%s' % self.vendor


class ShoppingService(Service):
    vendor = models.ForeignKey(Company, on_delete=models.DO_NOTHING, null=False)

    def __str__(self):
        return '%s' % self.vendor


class EventService(Service):
    EVENT_CHOICES = [
        ('Movie', 'Movie'),
        ('Concert', 'Concert'),
    ]
    location = models.ForeignKey(Location, on_delete=models.DO_NOTHING, null=False, related_name='location')
    event_type = models.CharField(max_length=10, choices=EVENT_CHOICES)


class OtherService(Service):
    pass


class ServiceMember(models.Model):
    service = models.ForeignKey(Service, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)


class Message(models.Model):
    timestamp = models.DateTimeField(auto_now=True)
    content = models.CharField(default='', max_length=1000)
    service = models.ForeignKey(Service, on_delete=models.DO_NOTHING, related_name="messages")
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, related_name="messages")

templates/services/create.html
<!DOCTYPE html>

{% load static %}
<html>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<head>
<style>
body {
  background-color: linen;
  margin: 10px;
}
hr {
    display: block;
    width: 400px;
    margin-before: 0.5em;
    margin-after: 0.5em;
    margin-start: auto;
    margin-end: auto;
    overflow: hidden;
    border-style: inset;
    border-width: 1px;
}

.row {
}

.left {
   display: inline-block;
   text-align: right;
   width: 100px;
   padding: 10px;
}


.right {
   display: inline-block;
   padding: 10px;
}

</style>


    <script>
  $(function () {
    $("#id_start_time").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
    </script>
</head>
<body>

{% block content %}
    <h2>New post</h2>
    <form method="POST">
        {% csrf_token %}
        <table border="1">

            {{ form }}
        </table>
        <br>
        <button type="submit">Submit</button>
    </form>

{% endblock %}

</body>

</html>

templates/services/integrated_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {% csrf_token %}
    <section>
        <div class="gap gray-bg">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row" id="page-contents">
                            {% include 'includes/sidebar.html' %}
                            <div class="col-lg-6">
                                <div class="central-meta">
                                    <div class="frnds">
                                        {#                                        <ul class="nav nav-tabs">#}
                                        <h5 class="f-title"><i class="ti-user"></i>Food Service</h5>
                                        {#                                        </ul>#}

                                        <div class="tab-content">
                                            <div class="tab-pane active fade show " id="frends">

                                                {#                                                insert stuff here#}

                                                <h2>Enter details:</h2>
                                                <form method="POST">
                                                    {% csrf_token %}
                                                    <table>
                                                        {{ form.as_p }}
                                                        <!--                                                        {{ form.media }}-->
                                                    </table>
                                                    <br>
                                                    <button type="submit">Submit</button>
                                                    <ul class="nearby-contct"  id="service_list">



                                                        {#                                                        INSERT HERE#}

                                                    </ul>
                                                </form>




                                                <div class="lodmore">
                                                    <button class="btn-view btn-load-more"></button>
                                                </div>

                                            </div>
                                            <script>
                                                function myFunction() {
                                                    window.open("/groups/create", "popup", 'width=400,height=300, top=400, left=700');
                                                }
                                            </script>

                                        </div>
                                    </div>
                                </div>
                            </div><!-- centerl meta -->
                        </div>
                    </div>
                </div><!-- friends list sidebar -->
                </aside>
            </div><!-- sidebar -->
        </div>
        </div>
        </div>
        </div>
        </div>
    </section>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>

        document.getElementById("id_start_time").addEventListener("change",fetchServices);
        document.getElementById("id_end_time").addEventListener("change",fetchServices);
        function fetchServices()

        {
            const instance = axios.create({
                baseURL: '{% url 'pool:home' %}',
                timeout: 1000,
            });

            var start= document.getElementById("id_start_time").value;
            var end= document.getElementById("id_end_time").value;
            if (start==undefined || end==undefined || start=="" || end=="")
            {
                start= undefined;
                end= undefined;
            }

            var cat_selected = "food";
            var gids_to_choose_from = "1,2";
            var all_gids = gids_to_choose_from.split(",");
            var selected_gids = all_gids;
            var select = document.getElementById("service_list");
            select.innerHTML = "";

            {#for (gid in all_gids)#}
            {#{#}
            {#    var selected = document.getElementById('group_' + all_gids[gid]).checked;#}
            {#    if (selected)#}
            {#    {#}
            {#        selected_gids.push(all_gids[gid]);#}
            {#    }#}
            {#}#}

                var gid_string =selected_gids.join(",");

                if (gid_string == "")
                {
                    return;
                }
                if (cat_selected == "food")
                {
                    instance.get('/api/foodservice', {
                        params: {
                            gids: gid_string,
                            start: start,
                            end: end
                        }
                    }).then(
                        function (response) {
                            reply = response.data;
                            console.log(reply);

                            for (item in reply)
                            {
                                {#here, reply[item] is our service object, can access fields directly,#}
                                select.innerHTML += "<li> <div class=\'nearly-pepls\'> <div class=\"pepl-info\">" +
                                    "<h4><a href=\"#\" title=\"\">Food Service</a></h4>" +
                                    "<a href=\"#\" title=\"\"><h5>" + reply[item].vendor + "</h5></a>" +
                                    "<p> by " + reply[item].initiator + "</p>" +
                                    "<h4><p>Start Time: " + reply[item].start_time + "<br> End Time: " + reply[item].end_time + "</p> </h4>" +
                                    "<span> " + reply[item].description + "</span>" +
                                    "<a href=\"#\" title=\"\" data-url=\"{% url 'groups:create' %}\" class=\"add-butn add-friend\" data-ripple=\"\">Join Service</a>"
                                    + "</div> </div> </li>";

                            }

                        }).catch(function (error) {
                        // handle error
                        alert(error);
                        console.log(error);
                    })
                }
                else if (cat_selected == "shopping")
                {
                    instance.get('/api/shoppingservice', {
                        params: {
                            gids: gid_string,
                            start: start,
                            end: end
                        }
                    }).then(
                        function (response) {
                            reply = response.data;
                            console.log(reply);

                            for (item in reply)
                            {
                                {#here, reply[item] is our service object, can access fields directly,#}
                                select.innerHTML += "<li> <div class=\'nearly-pepls\'> <div class=\"pepl-info\">" +
                                    "<h4><a href=\"#\" title=\"\">Shopping Service</a></h4>" +
                                    "<a href=\"#\" title=\"\"><h5>" + reply[item].vendor + "</h5></a>" +
                                    "<p> by " + reply[item].initiator + "</p>" +
                                    "<h4><p>Start Time: " + reply[item].start_time + "<br> End Time: " + reply[item].end_time + "</p> </h4>" +
                                    "<span> " + reply[item].description + "</span>" +
                                    "<a href=\"#\" title=\"\" data-url=\"{% url 'groups:create' %}\" class=\"add-butn add-friend\" data-ripple=\"\">Join Service</a>"
                                    + "</div> </div> </li>";
                            }
                        }).catch(function (error) {
                        // handle error
                        alert(error);
                        console.log(error);
                    })
                }
                else
                {
                    {#    travel#}
                    instance.get('/api/travelservice', {
                        params: {
                            gids: gid_string,
                            start: start,
                            end: end
                        }
                    }).then(
                        function (response) {
                            reply = response.data;
                            console.log(reply);

                            for (item in reply)
                            {
                                {#here, reply[item] is our service object, can access fields directly,#}
                                select.innerHTML += "<li> <div class=\'nearly-pepls\'> <div class=\"pepl-info\">" +
                                    "<h4><a href=\"#\" title=\"\">Travel Service</a></h4>" +
                                    "<a href=\"#\" title=\"\"><h5>" + "reply[item].vendor" + "</h5></a>" +
                                    "<p> by " + reply[item].initiator + "</p>" +
                                    "<h4><p>Source: " + reply[item].start_point + "<br> Destination: " + reply[item].end_point + "</p> </h4> <br>" +
                                    "<h4><p>Start Time: " + reply[item].start_time + "<br> End Time: " + reply[item].end_time + "</p> </h4>" +
                                    "<span> " + reply[item].description + "</span>" +
                                    "<a href=\"#\" title=\"\" data-url=\"{% url 'groups:create' %}\" class=\"add-butn add-friend\" data-ripple=\"\">Join Service</a>"
                                    + "</div> </div> </li>";
                            }
                        }).catch(function (error) {
                        // handle error
                        alert(error);
                        console.log(error);
                    })
                }
                {#console.log("new html");#}
                {#console.log(new_html);#}
                {#select.innerHTML = new_html;#}
            }
            window.onload=fetchServices;
    </script>
{% endblock %}

{% block footer %}
    <link rel="stylesheet" type="text/css" href="{% static 'autocomplete_light/select2.css' %}" />
    <script type="text/javascript" src="{% static 'autocomplete_light/jquery.init.js' %}"></script>
    <script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>
    <script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'autocomplete_light/vendor/select2/dist/css/select2.css' %}" />
    <script type="text/javascript" src="{% static 'autocomplete_light/vendor/select2/dist/js/select2.full.js' %}"></script>
    <script type="text/javascript" src="{% static 'autocomplete_light/forward.js' %}"></script>
    <!--    {{ form.media }}-->
{% endblock %}