accounts/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')]

api/urls.py
from django.urls import include, path, re_path
from .views import *
from rest_framework import routers

app_name = "api"

router = routers.DefaultRouter()
urlpatterns = [
    re_path(r'^foodservice$', FoodServiceList.as_view(), name='foodservice'),
    re_path(r'^travelservice$', TravelServiceList.as_view(), name='travelservice'),
    re_path(r'^shoppingservice$', ShoppingServiceList.as_view(), name='shoppingservice'),
    re_path(r'^eventservice$', EventServiceList.as_view(), name='eventservice'),
    re_path(r'^otherservice$', OtherServiceList.as_view(), name='otherservice'),
    re_path(r'^get_coordinates$', get_coordinates, name='get_coordinates'),

    re_path(r'^foodservicereco$', FoodServiceReco.as_view(), name='foodservicereco'),
    re_path(r'^travelservicereco$', TravelServiceReco.as_view(), name='travelservicereco'),
    re_path(r'^shoppingservicereco$', ShoppingServiceReco.as_view(), name='shoppingservicereco'),

]

pool/urls.py
from django.urls import path
from .views import *
from chat.views import food_index

app_name = "pool"

urlpatterns = [
    # path('create', ServiceCreateView.as_view(),name='create')
    # path('', home, name='home')
    path('', home, name='home')    # Making My Services the home page
]

superpool/urls.py
from django.contrib import admin
from django.urls import path, include
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('pool.urls')),
    path('groups/',include('groups.urls')),
    path('services/', include('services.urls')),
    path('chat/', include('chat.urls')),
    path('notification/', include('notification.urls')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('api/', include('api.urls')),
    path('activities/', include('activities.urls')),
    path('recommendations/', include('recommendations.urls')),
    path('location/', include('location.urls'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <title>SuperPool</title>

    {% include 'includes/stylesheets.html' %}
    {% csrf_token %}

</head>
<body>
<div class="theme-layout">

    <div class="topbar stick">
        <div class="logo">
            <a title="" href="/"><img src="{% static 'images/logo.png' %}" alt="" style="height: 70px; width: 90px"></a>
        </div>

        <div class="top-area">
            <div class="top-search">
                <form method="post" class="">
                    <input type="text" placeholder="Search For a Service">
                    <button data-ripple><i class="ti-search"></i></button>
                </form>
            </div>
            <ul class="setting-area">
<!--                <li><a href="'services:create'" title="New Post" data-ripple=""><i class="ti-plus"></i></a></li>-->
                <li><a href="{% url 'pool:home' %}" title="Home" data-ripple=""><i class="ti-home"></i></a></li>

<!--{#                <li><a href="{% url 'communications:all-messages' %}" class="link">Messenger</a></li>#}-->
<!--                <li>-->
<!--                    <a href="#" title="Notification" data-ripple="">-->
<!--                        <i class="ti-user"></i><span id="total-friend-notifications"></span>-->
<!--                    </a>-->
<!--                    <div class="dropdowns">-->
<!--                        <ul class="drops-menu" id="friend-menu">-->
<!--                        </ul>-->
<!--                        <a href="#" title="" class="more-mesg">view more</a>-->
<!--                    </div>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="#" title="Messages" data-ripple=""><i class="ti-comment"></i><span id="total-like-comment-notifications">0</span></a>-->
<!--                    <div class="dropdowns">-->
<!--                        <ul class="drops-menu" id="like-comment-menu">-->
<!--                        </ul>-->
<!--                        <a href="#" title="" class="more-mesg">view more</a>-->
<!--{#                        <a href="#" title="" class="more-mesg" data-url="{% url 'notifications:mark-like-comment-notifications-as-read' %}" id="mark-like-comment-notifications-as-read">mark all as read</a>#}-->
<!--                    </div>-->
<!--                </li>-->
            </ul>
            <div class="user-img">
{#                <img src="{{ request.user.profile.profile_image.url }}" alt="" style="height: 40px; width: 40px;">#}
                <span class="status f-online"></span>
                <div class="user-setting">
                    <a href="#" title=""><span class="status f-online"></span>online</a>
                    <a href="#" title=""><span class="status f-away"></span>away</a>
                    <a href="#" title=""><span class="status f-off"></span>offline</a>
                    <a href="#" title=""><i class="ti-user"></i> view profile</a>
{#                    <a href="{% url 'profile:edit-profile' %}" title=""><i class="ti-pencil-alt"></i>edit profile</a>#}
                    <a href="#" title=""><i class="ti-target"></i>activity log</a>
                    <a href="#" title=""><i class="ti-settings"></i>account setting</a>
                    <a href="{% url 'accounts:logout' %}" title=""><i class="ti-power-off"></i>log out</a>
                </div>
            </div>
            <span class="ti-menu main-menu" data-ripple=""></span>
        </div>
    </div><!-- topbar -->

    {% block content %}
    {% endblock %}

<!--    <footer>-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-lg-6 col-md-4">-->
<!--                    <div class="widget">-->
<!--                        <div class="widget-title"><h4>follow</h4></div>-->
<!--                        <ul class="list-style">-->
<!--                            <li><i class="fa fa-facebook-square"></i> <a href="https://web.facebook.com/shopcircut/" title="">facebook</a></li>-->
<!--                            <li><i class="fa fa-twitter-square"></i><a href="https://twitter.com/login?lang=en" title="">twitter</a></li>-->
<!--                            <li><i class="fa fa-instagram"></i><a href="https://www.instagram.com/?hl=en" title="">instagram</a></li>-->
<!--                            <li><i class="fa fa-google-plus-square"></i> <a href="https://plus.google.com/discover" title="">Google+</a></li>-->
<!--                            <li><i class="fa fa-pinterest-square"></i> <a href="https://www.pinterest.com/" title="">Pintrest</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-lg-6 col-md-4">-->
<!--                    <div class="widget">-->
<!--                        <div class="widget-title"><h4>useful links</h4></div>-->
<!--                        <ul class="list-style">-->
<!--                            <li><a href="#" title="">leasing</a></li>-->
<!--                            <li><a href="#" title="">submit route</a></li>-->
<!--                            <li><a href="#" title="">how does it work?</a></li>-->
<!--                            <li><a href="#" title="">agent listings</a></li>-->
<!--                            <li><a href="#" title="">view All</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </footer>&lt;!&ndash; footer &ndash;&gt;-->
<!--    <div class="bottombar">-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-md-12">-->
<!--                    <span class="copyright">©. All rights reserved.</span>-->
<!--                    <i><img src="images/credit-cards.png" alt=""></i>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
</div>
{% include 'includes/scripts.html' %}
<!--{% block scripts %}{% endblock %}-->

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<head>
<script type="text/javascript">
window.onload = function(){
    if({{ message }}==1) {
        alert("Added to group successfully");
    }

    if({{ message }}==2) {
        alert("Food Service registered successfully");
    }

    if({{ message }}==3) {
        alert("Shopping Service registered successfully");
    }

    if({{ message }}==4) {
        alert("Travel Service registered successfully");
    }

    if({{ message }}==5) {
        alert("Event Service registered successfully");
    }

    if({{ message }}==6) {
        alert("Service registered successfully");
    }
}
</script>
</head>
<body>
<script>
function alertFunc() {
  alert("Page is loaded");
}
</script>
    <section>
        <div class="gap gray-bg">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row" id="page-contents">
                            {% include 'includes/sidebar.html' %}
                            <div class="col-lg-6">
                                <div class="central-meta">
                                    <div class="new-postbox">
                                        <figure>
                                            <img src="{{ request.user.profile.profile_image.url }}" alt="">
                                        </figure>
                                        <div class="newpst-input">
                                            {#                                            <form method="post" action="{% url 'newsfeed:post-create' %}">#}
                                            {% csrf_token %}
                                            <textarea rows="2" name="body" placeholder="Write something"></textarea>
                                            <div class="attachments">
                                                <ul>
                                                    <li>
                                                        <i class="fa fa-music"></i>
                                                        <label class="fileContainer">
                                                            <input type="file">
                                                        </label>
                                                    </li>
                                                    <li>
                                                        <i class="fa fa-image"></i>
                                                        <label class="fileContainer">
                                                            <input type="file">
                                                        </label>
                                                    </li>
                                                    <li>
                                                        <i class="fa fa-video-camera"></i>
                                                        <label class="fileContainer">
                                                            <input type="file">
                                                        </label>
                                                    </li>
                                                    <li>
                                                        <i class="fa fa-camera"></i>
                                                        <label class="fileContainer">
                                                            <input type="file">
                                                        </label>
                                                    </li>
                                                    <li>
                                                        <button type="submit">Post</button>
                                                    </li>
                                                </ul>
                                            </div>
                                            {#                                            </form>#}
                                        </div>
                                    </div>
                                </div><!-- add post new box -->
                                <div class="loadMore">

                                </div>
                            </div><!-- centerl meta -->
<!--                            <div class="col-lg-3">-->
<!--                                <aside class="sidebar static">-->
<!--                                    <div class="widget friend-list stick-widget">-->
<!--                                        <h4 class="widget-title">Friends</h4>-->
<!--                                        <div id="searchDir"></div>-->
<!--                                        <ul id="people-list" class="friendz-list">-->
<!--                                            {#                                            {% for friend in friends %}#}-->
<!--                                            {#                                                <li>#}-->
<!--                                            {#                                                    <figure>#}-->
<!--                                            {#                                                        <img src="images/resources/friend-avatar.jpg" alt="">#}-->
<!--                                            {#                                                        <span class="status f-online"></span>#}-->
<!--                                            {#                                                    </figure>#}-->
<!--                                            {#                                                    <div class="friendz-meta">#}-->
<!--                                            {#                                                        <a href="time-line.html">{{ friend.user.username }}</a>#}-->
<!--                                            {#                                                        <i><a href="https://wpkixx.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="07706e6973627574686b63627547606a666e6b2964686a">[email&#160;protected]</a></i>#}-->
<!--                                            {#                                                    </div>#}-->
<!--                                            {#                                                </li>#}-->
<!--                                            {#                                            {% endfor %}#}-->
<!--                                        </ul>-->
<!--                                        <div class="chat-box">-->
<!--                                            <div class="chat-head">-->
<!--                                                <span class="status f-online"></span>-->
<!--                                                <h6>Bucky Barnes</h6>-->
<!--                                                <div class="more">-->
<!--                                                    <span><i class="ti-more-alt"></i></span>-->
<!--                                                    <span class="close-mesage"><i class="ti-close"></i></span>-->
<!--                                                </div>-->
<!--                                            </div>-->
<!--                                            <div class="chat-list">-->
<!--                                                <ul>-->
<!--                                                    <li class="me">-->
<!--                                                        <div class="chat-thumb"><img src="images/resources/chatlist1.jpg" alt=""></div>-->
<!--                                                        <div class="notification-event">-->
<!--															<span class="chat-message-item">-->
<!--																Hi James! Please remember to buy the food for tomorrow! I’m gonna be handling the gifts and Jake’s gonna get the drinks-->
<!--															</span>-->
<!--                                                            <span class="notification-date"><time datetime="2004-07-24T18:18" class="entry-date updated">Yesterday at 8:10pm</time></span>-->
<!--                                                        </div>-->
<!--                                                    </li>-->
<!--                                                    <li class="you">-->
<!--                                                        <div class="chat-thumb"><img src="images/resources/chatlist2.jpg" alt=""></div>-->
<!--                                                        <div class="notification-event">-->
<!--															<span class="chat-message-item">-->
<!--																Hi James! Please remember to buy the food for tomorrow! I’m gonna be handling the gifts and Jake’s gonna get the drinks-->
<!--															</span>-->
<!--                                                            <span class="notification-date"><time datetime="2004-07-24T18:18" class="entry-date updated">Yesterday at 8:10pm</time></span>-->
<!--                                                        </div>-->
<!--                                                    </li>-->
<!--                                                    <li class="me">-->
<!--                                                        <div class="chat-thumb"><img src="images/resources/chatlist1.jpg" alt=""></div>-->
<!--                                                        <div class="notification-event">-->
<!--															<span class="chat-message-item">-->
<!--																Hi James! Please remember to buy the food for tomorrow! I’m gonna be handling the gifts and Jake’s gonna get the drinks-->
<!--															</span>-->
<!--                                                            <span class="notification-date"><time datetime="2004-07-24T18:18" class="entry-date updated">Yesterday at 8:10pm</time></span>-->
<!--                                                        </div>-->
<!--                                                    </li>-->
<!--                                                </ul>-->
<!--                                                <form class="text-box">-->
<!--                                                    <textarea placeholder="Post enter to post..."></textarea>-->
<!--                                                    <div class="add-smiles">-->
<!--                                                        <span title="add icon" class="em em-expressionless"></span>-->
<!--                                                    </div>-->
<!--                                                    <div class="smiles-bunch">-->
<!--                                                        <i class="em em-&#45;&#45;1"></i>-->
<!--                                                        <i class="em em-smiley"></i>-->
<!--                                                        <i class="em em-anguished"></i>-->
<!--                                                        <i class="em em-laughing"></i>-->
<!--                                                        <i class="em em-angry"></i>-->
<!--                                                        <i class="em em-astonished"></i>-->
<!--                                                        <i class="em em-blush"></i>-->
<!--                                                        <i class="em em-disappointed"></i>-->
<!--                                                        <i class="em em-worried"></i>-->
<!--                                                        <i class="em em-kissing_heart"></i>-->
<!--                                                        <i class="em em-rage"></i>-->
<!--                                                        <i class="em em-stuck_out_tongue"></i>-->
<!--                                                    </div>-->
<!--                                                    <button type="submit"></button>-->
<!--                                                </form>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>&lt;!&ndash; friends list sidebar &ndash;&gt;-->
                                </aside>
                            </div><!-- sidebar -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

{% endblock %}